[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/themes/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000, immutable"

[[plugins]]
  package = "./netlify/plugins/migrate-to-cloudflare"

[[plugins]]
  package = "./netlify/plugins/backfill-thumbnails"
